### ISSUE TITLE
Drop Travis CI

### ISSUE THREAD

**Issue by nlohmann** [nlohmann/json#3087]
# Background

Travis CI went to a paid model, and open source projects need to apply for credits to continue using Travis CI for free. This process is cumbersome as it requires to send an email to get 25,000 credits. During normal development, these credits only last a few days. Topping up the credits requires sending another email. This is effort I am no longer willing to invest.

# Todo

- [x] Remove `.travis.yml` file.
- [x] Overworkd `README.md` file and in particular edit the list of compilers.
- [x] Check if we have support for GCC 6 and Xcode 10.2 somewhere else.
- [x] Check if integrating Coverity somewhere else is possible.
